export enum ScrollCostEnum {
  SCROLLS_6 = "SCROLLS_6",
  SCROLLS_8 = "SCROLLS_8",
  SCROLLS_10 = "SCROLLS_10",
  SCROLLS_12 = "SCROLLS_12",
  SCROLLS_16 = "SCROLLS_16",
  SCROLLS_18 = "SCROLLS_18",
  SCROLLS_24 = "SCROLLS_24",
  SCROLLS_30 = "SCROLLS_30",
  SCROLLS_32 = "SCROLLS_32",
  SCROLLS_36 = "SCROLLS_36",
  SCROLLS_40 = "SCROLLS_40",
  SCROLLS_42 = "SCROLLS_42",
  SCROLLS_48 = "SCROLLS_48",
  SCROLLS_54 = "SCROLLS_54",
  SCROLLS_56 = "SCROLLS_56",
  SCROLLS_60 = "SCROLLS_60",
  SCROLLS_64 = "SCROLLS_64",
  SCROLLS_66 = "SCROLLS_66",
  SCROLLS_72 = "SCROLLS_72",
  SCROLLS_78 = "SCROLLS_78",
  SCROLLS_80 = "SCROLLS_80",
  SCROLLS_84 = "SCROLLS_84",
  SCROLLS_88 = "SCROLLS_88",
  SCROLLS_90 = "SCROLLS_90",
  SCROLLS_96 = "SCROLLS_96",
}

export const ScrollCostEnumLabel: Record<ScrollCostEnum, string> = {
  [ScrollCostEnum.SCROLLS_6]: "6 Scrolls",
  [ScrollCostEnum.SCROLLS_8]: "8 Scrolls",
  [ScrollCostEnum.SCROLLS_10]: "10 Scrolls",
  [ScrollCostEnum.SCROLLS_12]: "12 Scrolls",
  [ScrollCostEnum.SCROLLS_16]: "16 Scrolls",
  [ScrollCostEnum.SCROLLS_18]: "18 Scrolls",
  [ScrollCostEnum.SCROLLS_24]: "24 Scrolls",
  [ScrollCostEnum.SCROLLS_30]: "30 Scrolls",
  [ScrollCostEnum.SCROLLS_32]: "32 Scrolls",
  [ScrollCostEnum.SCROLLS_36]: "36 Scrolls",
  [ScrollCostEnum.SCROLLS_40]: "40 Scrolls",
  [ScrollCostEnum.SCROLLS_42]: "42 Scrolls",
  [ScrollCostEnum.SCROLLS_48]: "48 Scrolls",
  [ScrollCostEnum.SCROLLS_54]: "54 Scrolls",
  [ScrollCostEnum.SCROLLS_56]: "56 Scrolls",
  [ScrollCostEnum.SCROLLS_60]: "60 Scrolls",
  [ScrollCostEnum.SCROLLS_64]: "64 Scrolls",
  [ScrollCostEnum.SCROLLS_66]: "66 Scrolls",
  [ScrollCostEnum.SCROLLS_72]: "72 Scrolls",
  [ScrollCostEnum.SCROLLS_78]: "78 Scrolls",
  [ScrollCostEnum.SCROLLS_80]: "80 Scrolls",
  [ScrollCostEnum.SCROLLS_84]: "84 Scrolls",
  [ScrollCostEnum.SCROLLS_88]: "88 Scrolls",
  [ScrollCostEnum.SCROLLS_90]: "90 Scrolls",
  [ScrollCostEnum.SCROLLS_96]: "96 Scrolls",
};

export const ScrollCostEnumNumber: Record<ScrollCostEnum, number> = {
  [ScrollCostEnum.SCROLLS_6]: 6,
  [ScrollCostEnum.SCROLLS_8]: 8,
  [ScrollCostEnum.SCROLLS_10]: 10,
  [ScrollCostEnum.SCROLLS_12]: 12,
  [ScrollCostEnum.SCROLLS_16]: 16,
  [ScrollCostEnum.SCROLLS_18]: 18,
  [ScrollCostEnum.SCROLLS_24]: 24,
  [ScrollCostEnum.SCROLLS_30]: 30,
  [ScrollCostEnum.SCROLLS_32]: 32,
  [ScrollCostEnum.SCROLLS_36]: 36,
  [ScrollCostEnum.SCROLLS_40]: 40,
  [ScrollCostEnum.SCROLLS_42]: 42,
  [ScrollCostEnum.SCROLLS_48]: 48,
  [ScrollCostEnum.SCROLLS_54]: 54,
  [ScrollCostEnum.SCROLLS_56]: 56,
  [ScrollCostEnum.SCROLLS_60]: 60,
  [ScrollCostEnum.SCROLLS_64]: 64,
  [ScrollCostEnum.SCROLLS_66]: 66,
  [ScrollCostEnum.SCROLLS_72]: 72,
  [ScrollCostEnum.SCROLLS_78]: 78,
  [ScrollCostEnum.SCROLLS_80]: 80,
  [ScrollCostEnum.SCROLLS_84]: 84,
  [ScrollCostEnum.SCROLLS_88]: 88,
  [ScrollCostEnum.SCROLLS_90]: 90,
  [ScrollCostEnum.SCROLLS_96]: 96,
};
